services:
  - type: web
    name: cyber-fort
    env: node
    buildCommand: npm install && npx vite build && esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VIRUSTOTAL_API_KEY
        sync: false
    healthCheckPath: /api/check-url
    autoDeploy: true 